### ISSUE TITLE
Sounds + VFX Missing 

### ISSUE THREAD

**Issue by Honey2339** [xJAPster/Bitwise-XO#2]
I see that sounds and vfx are missing and it makes it boring :(

**Comment by xJAPster** [comment]
working on it. will roll it out in the next patch :D

**Comment by xJAPster** [comment]
hey @Honey2339,

i've rolled out some basic sound effects with #3 , and you can be sure that VFX is soon to follow ;)

**Comment by Honey2339** [comment]
LGTM waiting for VFX :D

**Comment by xJAPster** [comment]
for now i've decided to implement a simple color coded rain of confetti for the victor. ill add some more effects later but for now this should suffice ;)

refer commit 96c58dce12e3b38ccdd3422caf86bf2de5316cb2

thanks for opening this issue ! :D
